# Generated by Django 4.2.3 on 2023-08-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intituler', models.CharField(max_length=255)),
                ('matiere', models.CharField(max_length=255)),
                ('projet', models.FileField(upload_to='projet_pdfs/')),
                ('statut', models.CharField(max_length=100)),
            ],
        ),
    ]
